name: "Weather Prediction ML"
version: "2.0.0"
slug: "weather_prediction_ml"
description: "Machine learning weather prediction with 82.2% accuracy using ensemble models"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/Maheidem/weather-prediction-ml-addon"
startup: "application"
boot: "auto"
init: false
options:
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "addons"
  mqtt_password: ""
  update_interval: 3600
  temperature_sensor: "sensor.sensor_varanda_temperature"
  humidity_sensor: "sensor.sensor_varanda_humidity"
  pressure_sensor: "sensor.sensor_varanda_pressure"
  log_level: "INFO"
schema:
  mqtt_broker: "str"
  mqtt_port: "port"
  mqtt_username: "str"
  mqtt_password: "password"
  update_interval: "int(300,86400)"
  temperature_sensor: "str"
  humidity_sensor: "str"
  pressure_sensor: "str"
  log_level: list(DEBUG|INFO|WARNING|ERROR)
services:
  - "mqtt:need"
homeassistant_api: true
image: "ghcr.io/maheidem/{arch}-weather-prediction-ml"